### ISSUE TITLE
WakaTime for PowerShell

### ISSUE THREAD

**Issue by mpearon** [irondoge/bash-wakatime#8]
Could this be ported to PowerShell?
We can overload the Prompt Function there as well - but I don't know enough about Bash to translate and build the same thing up there.

**Comment by mpearon** [comment]
@irondoge - Is this something you might know anything about?  I mentioned your work over [here](https://github.com/wakatime/wakatime/issues/126).

**Comment by irondoge** [comment]
See my answer in the refered issue

**Comment by Gravifer** [comment]
I gathered the code by @iamkarlson @mpearon et al. in related threads, and pushed a module named posh-wakatime to the PSGallery. It is still at an early stage, and any help is welcome at the [repo](https://github.com/Gravifer/posh-wakatime). I haven't sort out the contribution yet, and copyright informations need to be updated, too.
